import { readFileSync } from 'node:fs';
import { createRequire } from 'node:module';
const require = createRequire('/var/www/vhosts/jbhasesorialegal.com/portal/apps/portal/server.js');
const url = readFileSync('/var/www/vhosts/jbhasesorialegal.com/shared/portal.env','utf8').split('\n').find(l=>l.startsWith('DATABASE_URL='))?.split('=').slice(1).join('=').trim().replace(/^["']|["']$/g,'');
const mysql = require('mysql2/promise'); const c = await mysql.createConnection(url);
const COLAB='31babca6-5b81-11f1-88c8-ee5423879f46';
const [cc] = await c.query("SELECT case_id FROM case_collaborators WHERE user_id=?",[COLAB]);
console.log('co-letrado en N casos:', cc.length, cc.map(x=>x.case_id.slice(0,8)).join(','));
const [lead] = await c.query("SELECT id FROM cases WHERE lead_lawyer_id=?",[COLAB]);
console.log('lead en N casos:', lead.length);
await c.end();
